[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.normal]
black = "#2e2e2e"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#101421"
foreground = "#fffbf6"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10

# [font.normal]
# family = "Hack Nerd Font Mono"
# style = "Regular"

# [[hints.enabled]]
# command = "xdg-open"
# hyperlinks = true
# post_processing = true

# [hints.enabled.mouse]
# enabled = true
# mods = "none"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
